compte/urls.py
from django.urls import path 
from . import views

from .custom_views import CreatePlanView, ListPlanView, CreatePlanView2

app_name = 'compte'

custom_patterns = [
    path('create-plan/', CreatePlanView.as_view(), name='create-plan'),
    path('create-plan2/', CreatePlanView2.as_view(), name='create-plan2'),
    path('list-plan/', ListPlanView.as_view(), name='list-plan'),
]


urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('activate/<uid64>/<token>/', views.activate, name="activate"),
    path('logout/', views.logout_view, name='logout'),
    path('reset-password-email/', views.ResetPassworLinkView.as_view(), name='reset-password-email'),
    path('reset-password/<uid64>/<token>/', views.password_reset_verification, name='reset-password-verify'),
    path('reset-password-complete/', views.password_reset_html, name='reset-password-complete'),
]


urlpatterns += custom_patterns


# Bon  a savoir django possede de vue preconstruite 

# exemple:

from django.contrib.auth import views as auth_views
from django.urls import path

urlpatterns = [
    # ... your other URL patterns ...

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

dashboard/urls.py
from django.urls import path 
from . import views 

app_name = 'dashboard'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('student/', views.student_dashboard, name='student-dashboard'),
    path('payment/', views.payment, name='payment'),
    path('task/', views.my_task_view, name='task'),
    path('task_result/<str:task_id>/', views.my_task_result, name='task-result'),
]

easy_dea/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path


## about/fr

urlpatterns = i18n_patterns(
    path("easy-dea-admin/", admin.site.urls),
    path("", include("main_app.urls")),
    path('compte/', include('compte.urls')),
    path('dashboard/', include('dashboard.urls')),
    
)

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


"""

from main_app import views

from main_app.custom_views.accounts import (
    RegisterView,
    SignupView,
)

from main_app.views import (
    MyView,
    HomePageView,
    AboutUsView,
    AboutView, 
    TermOfUseView,
    PrivacyPolicyView,
    SupportView,
    ContactUsView,
    ComplaintsView,
    FeedbackView,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main_app.urls")),
    path("home/", HomePageView.as_view(), name="home"),

    path('hello/', views.hello),
    path("mine/", MyView.as_view(), name="my-view"),
    
  #  path("about-us/", AboutUsView.as_view(), name="about-us"),
    path('about-us/', AboutView.as_view(), name='about-us'),
    path("term-of-use", TermOfUseView.as_view(), name="term-of-use"),
    path("privacy-policy", PrivacyPolicyView.as_view(), name="privacy-policy"),
    path("support", SupportView.as_view(), name="support"),
    path("contact-us", ContactUsView.as_view(), name="contact-us"),
    path("complaints", ComplaintsView.as_view(), name="complaints"),
    path("feedback", FeedbackView.as_view(), name="feedback"),
    
    path("sign-up", SignupView.as_view(), name="sign-up"),
    path("register", RegisterView.as_view(), name="register"),
    
]
"""

dashboard/models.py
from django.db import models

# Create your models here.

compte/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View
from .models import User
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail, EmailMessage

from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string

from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str

from .token import TokenGenerator

from .utils import send_email_with_html

generateToken = TokenGenerator()

def signup_view(request):
    
    if request.method == 'POST':
        email = request.POST.get('email')
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        
        if password1 == password2:
            if User.objects.filter(email=email).exists():
                messages.info(request, 'Email already exists')
                return redirect('compte:signup')
            elif User.objects.filter(username=username).exists():
                messages.info(request, 'Username already exists')
                return redirect('compte:signup')
            else:
                user = User.objects.create_user(email=email, username=username, first_name=first_name, last_name=last_name, password=password1)
                user.is_active = False
                user.save()
                
                # welcome email 
                subject = " Welcome "
                message = f"Hi,{first_name} {last_name}, welcome on DEA your account has been created successfully."
                from_email = settings.EMAIL_HOST_USER
                to_email = [user.email]
                send_mail(subject, message, from_email, to_email, fail_silently=False)
                
                # activation email 
                current_site = get_current_site(request)
                email_subject = " confirm your email on DEA"
                context =  {
                        'name': f"{first_name} {last_name}",
                        'domain': current_site.domain,
                        'uid':  urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': generateToken.make_token(user)
                    }
                template_name = 'emailconfirm.html'
                
                send_email_with_html(context, template_name, email_subject, from_email, to_email)
                
                messages.success(request, 'Account created successfully but not yet activated till you confirm your email address')
                
                return redirect('compte:login')
        else:
            messages.error(request, "the two password must match")    
            
    return render(request, 'signup.html')


class ResetPassworLinkView(View):
    
    template_name = 'reset.html'
    
    
    def get(self, request,  *ags, **kwargs):
        return render(request, self.template_name)
    
    
    def post(self, request,  *args, **kwargs):
        
        email = request.POST.get('email')
        
        if User.objects.filter(email=email).exists():
            user = User.objects.get(email=email)
            
            from_email = settings.EMAIL_HOST_USER
            to_email = [user.email]
            
            # reset email 
            current_site = get_current_site(request)
            email_subject = " reset your password on DEA"
            context =  {
                    'name': f"{user.first_name} {user.last_name}",
                    'domain': current_site.domain,
                    'uid':  urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': generateToken.make_token(user)
                }
            email_template_name = 'email_reset_password.html'
            
            send_email_with_html(context, email_template_name, email_subject, from_email, to_email)
            
            messages.success(request, "check your mail box to reset your password")
        
        return render(request, self.template_name)


def password_reset_verification(request, uid64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uid64))
        my_user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        my_user = None 
    
    if my_user is not None and generateToken.check_token(my_user, token):
        request.session['user_id'] = my_user.id
        messages.success(request, "Your can reset your password now")    
        return redirect('compte:reset-password-complete')
        
    else:
        messages.error(request, "reset failed try again")  
        
    return redirect('compte:reset-password-email') 


def password_reset_html(request):
    if request.method == 'POST':
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        
        if password1 == password2:
            user_id = request.session.get('user_id')
            user = User.objects.get(pk=user_id)
            user.set_password(password1)
            user.save()
            
            # Clear the session data after successful password reset
            del request.session['user_id']

            messages.success(request, "Your password has been reset successfully") 
            return redirect('compte:login')   
        else:
            messages.error(request, "the two password must match")

    return render(request, 'reset_password_form.html')

def login_view(request):
    next = request.GET.get('next')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)
        __user = User.objects.filter(username=username)
        if __user:
            if __user.first().is_active:
                if user is not None:
                    if user.is_active:
                        
                        login(request, user)
                        
                        messages.success(request, 'welcome back login has been done successfully')
                        
                        if next:
                            return redirect(next)
                        else:
                            return redirect('dashboard:dashboard')
                                   
                    else:
                        messages.info(request, 'Sorry you didn\'t confirm your account')    
                
                else:
                    messages.error(request, 'sorry your username and password didn\'t match')
                    return redirect('compte:login') 
            else:
                messages.info(request, 'Sorry you didn\'t confirm your account')        
    return render(request, 'login.html')



def activate(request, uid64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uid64))
        my_user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        my_user = None 
    
    if my_user is not None and generateToken.check_token(my_user, token):
        my_user.is_active = True 
        my_user.save()  
        messages.success(request, "Your account has been activated you can login now")    
    else:
        messages.error(request, "Activation failed try again")  
        
    return redirect('compte:login')        



def logout_view(request):
    logout(request)
    messages.success(request, 'Your logged out')
    return redirect('compte:login')

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.contrib import messages
from compte.permissions import role_required, RoleRequiredMixin, GroupRequiredMixin, group_required
from compte.models import Plan, SubcribePlam
from .task import add

class DashboardView(GroupRequiredMixin, View):
    group_required = ['basic', 'premium', 'New']
    template_name = 'dash/dashboard.html'
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})


class AnalysComplexDataView(GroupRequiredMixin, View):
    group_required = ['premium']
    template_name = 'dash/analys_complex_data.html'
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})
    

class AnalysSimpleDataView(GroupRequiredMixin, View):
    group_required = ['New']
    template_name = 'dash/analys_simple_data.html'
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})
    
    
@group_required(['basic'])
def student_dashboard(request):
    
    user = request.user 
    
    if user.has_perm('compte.can_view_payment_history'): #app_label.codename
        
        messages.info(request, 'you can view payment history ')
    else:
        messages.info(request, 'you can not view payment history')   
        
    if user.groups.filter(name='basic').exists():
        messages.info(request, 'you are in basic group')     

    return render(request, 'dash/student_dashboard.html')


from django.contrib.auth.models import Group, Permission
import datetime 


def payment(request, *args, **kwargs):
    plans = Plan.objects.all()
    
    if request.method == 'POST':
        user = request.user 
        plan_id = request.POST.get('type_plan')
        
        period = request.POST.get('period')
        if plan_id == 'premium':
            if period=='monthly':
                SubcribePlam.objects.create(user=user, plan_id=plan_id,
                                            start_date=datetime.datetime.now(),
                                            end_date=datetime.datetime.now() + datetime.timedelta(days=30))
            elif period == 'yearly':
                
                SubcribePlam.objects.create(user=user, plan_id=plan_id,
                                            start_date=datetime.datetime.now(),
                                            end_date=datetime.datetime.now() + datetime.timedelta(days=365))
                    
            permission = Permission.objects.get(codename='can_view_payment_history')
            
            user.user_permissions.add(permission)
            
            messages.info(request, 'you have  been added to view history payment')
            
            groups = Group.objects.filter(name__in=['premium', 'basic', 'New'])
        
        
            user.groups.set(groups)
            
            messages.info(request, 'you have  been added to basic group')
            
            messages.success(request, 'you have successfully subscribed to a plan')
            
        elif plan_id == 'basic':
            SubcribePlam.objects.create(user=user, plan_id=plan_id,
                                        start_date='2023-10-05',
                                        end_date='2023-12-01')
            
            groups = Group.objects.filter(name__in=['basic', 'New'])
        
        
            user.groups.set(groups)
            
            messages.info(request, 'you have  been added to basic group')
            
            messages.success(request, 'you have successfully subscribed to a plan')   
        else:
            SubcribePlam.objects.create(user=user, plan_id=plan_id,
                                        start_date='2023-10-05',
                                        end_date='2023-12-01')
            
            groups = Group.objects.filter(name__in=['New'])
        
        
            user.groups.set(groups)
            
            messages.info(request, 'you have  been added to New group')
            
            messages.success(request, 'you have successfully subscribed to a plan')     
    return render(request, 'dash/payment.html', {'plans': plans})


def my_task_view(request):
    
    result = add.delay(2, 3)
    
    print(result)

    return render(request, 'dash/my_task.html', {'result': result})


def my_task_result(request, task_id):

    result = add.AsyncResult(task_id)
    
    if result.ready():

        return render(request, 'dash/my_task_result.html', {'result': result.result})
    
    else:
        return render(request, 'dash/my_task_result.html', {'result': 'task is not ready still running'})
    

compte/templates/dashboard.html
{% if request.user.is_staff%}

<a>Staff</a>

{% elif request.user.is_or %}

<a>OR</a>

{% elif request.user.is_ee %}


{%  endif %}

compte/templates/email_reset_password.html
{% autoescape off %}


Hi {{ name }}!

Someone ask to reset your password. If it was you, please click on the link below to reset your password:


confirm link: http//{{domain}}{% url 'compte:reset-password-verify' uid64=uid token=token  %}

if not, please ignore this email.

{% endautoescape %}

compte/templates/emailconfirm.html
{% autoescape off %}


welcome to DEA

Please confirm your email by clicking on the link below 

confirm link: http//{{domain}}{% url 'compte:activate' uid64=uid token=token  %}

{% endautoescape %}

compte/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
</head>

<h1> Login Here </h1>

{% if messages %}

        {% for message in messages %}

        <p style="color: green"> {{ message }}</p>

        {% endfor %}

{% endif %}

<body>

    <form method="post">

        {% csrf_token %}

        <label id="username"> username </label>

        <input for="username" type="text"  name="username" placeholder="enter your username">

        <label id="password1"> password </label>
        <input for="password1" type="password" name="password" placeholder="enter your password1">



         
        <button type="submit"> login </button>

    </form>
    
</body>
</html>

compte/templates/reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>register </title>
</head>

<h1> Email to reset password </h1>

{% if messages %}

        {% for message in messages %}

        <p style="color: green"> {{ message }}</p>

        {% endfor %}

{% endif %}


<body>

    <form method="post">

        {% csrf_token %}

       
        <label id="email"> email </label>
        <input for="email" type="email" name="email" placeholder="enter your email address">
        <br><br>



       

        <button type="submit"> reset now </button>

    </form>
    
</body>
</html>

compte/templates/reset_password_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>register </title>
</head>

<h1> Reset password here </h1>

{% if messages %}

        {% for message in messages %}

        <p style="color: green"> {{ message }}</p>

        {% endfor %}

{% endif %}


<body>

    <form method="post">

        {% csrf_token %}

       
        <label id="password1"> password </label>
        <input for="password1" type="password" name="password1" placeholder="enter your password1">
        <br><br>



        <label id="password2"> confirm password </label>
        <input for="password2" type="password" name="password2" placeholder="enter your password2">

        <br><br>


        <button type="submit"> reset now </button>

    </form>
    
</body>
</html>

compte/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>register </title>
</head>

<h1> Register here </h1>

{% if messages %}

        {% for message in messages %}

        <p style="color: green"> {{ message }}</p>

        {% endfor %}

{% endif %}


<body>

    <form method="post">

        {% csrf_token %}

        <label id="username"> username </label>
        <input for="username" type="text"  name="username" placeholder="enter your username">
<br><br>

        <label id="email"> Email </label>
        <input for="email" type="email"  name="email" placeholder="enter your email">
        <br><br>


        <label id="first-name"> First name </label>
        <input for="first-name" type="text" name="first_name" placeholder="enter your firstn ame">
        <br>
        <br>

        <label id="last-name"> Last name </label>
        <input for="last-name" type="text" name="last_name" placeholder="enter your last name">
        <br><br>


        <label id="password1"> password </label>
        <input for="password1" type="password" name="password1" placeholder="enter your password1">
        <br><br>



        <label id="password2"> confirm password </label>
        <input for="password2" type="password" name="password2" placeholder="enter your password2">

        <br><br>


        <button type="submit"> create </button>

    </form>
    
</body>
</html>