compte/urls.py
from django.urls import path 
from . import views

from .custom_views import CreatePlanView, ListPlanView, CreatePlanView2

app_name = 'compte'

custom_patterns = [
    path('create-plan/', CreatePlanView.as_view(), name='create-plan'),
    path('create-plan2/', CreatePlanView2.as_view(), name='create-plan2'),
    path('list-plan/', ListPlanView.as_view(), name='list-plan'),
]


urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('activate/<uid64>/<token>/', views.activate, name="activate"),
    path('logout/', views.logout_view, name='logout'),
    path('reset-password-email/', views.ResetPassworLinkView.as_view(), name='reset-password-email'),
    path('reset-password/<uid64>/<token>/', views.password_reset_verification, name='reset-password-verify'),
    path('reset-password-complete/', views.password_reset_html, name='reset-password-complete'),
]


urlpatterns += custom_patterns


# Bon  a savoir django possede de vue preconstruite 

# exemple:

from django.contrib.auth import views as auth_views
from django.urls import path

urlpatterns = [
    # ... your other URL patterns ...

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

dashboard/urls.py
from django.urls import path 
from . import views 

app_name = 'dashboard'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('student/', views.student_dashboard, name='student-dashboard'),
    path('payment/', views.payment, name='payment'),
    path('task/', views.my_task_view, name='task'),
    path('task_result/<str:task_id>/', views.my_task_result, name='task-result'),
]

easy_dea/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path


## about/fr

urlpatterns = i18n_patterns(
    path("easy-dea-admin/", admin.site.urls),
    path("", include("main_app.urls")),
    path('compte/', include('compte.urls')),
    path('dashboard/', include('dashboard.urls')),
    
)

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


"""

from main_app import views

from main_app.custom_views.accounts import (
    RegisterView,
    SignupView,
)

from main_app.views import (
    MyView,
    HomePageView,
    AboutUsView,
    AboutView, 
    TermOfUseView,
    PrivacyPolicyView,
    SupportView,
    ContactUsView,
    ComplaintsView,
    FeedbackView,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main_app.urls")),
    path("home/", HomePageView.as_view(), name="home"),

    path('hello/', views.hello),
    path("mine/", MyView.as_view(), name="my-view"),
    
  #  path("about-us/", AboutUsView.as_view(), name="about-us"),
    path('about-us/', AboutView.as_view(), name='about-us'),
    path("term-of-use", TermOfUseView.as_view(), name="term-of-use"),
    path("privacy-policy", PrivacyPolicyView.as_view(), name="privacy-policy"),
    path("support", SupportView.as_view(), name="support"),
    path("contact-us", ContactUsView.as_view(), name="contact-us"),
    path("complaints", ComplaintsView.as_view(), name="complaints"),
    path("feedback", FeedbackView.as_view(), name="feedback"),
    
    path("sign-up", SignupView.as_view(), name="sign-up"),
    path("register", RegisterView.as_view(), name="register"),
    
]
"""

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.contrib import messages
from compte.permissions import role_required, RoleRequiredMixin, GroupRequiredMixin, group_required
from compte.models import Plan, SubcribePlam
from .task import add

class DashboardView(GroupRequiredMixin, View):
    group_required = ['basic', 'premium', 'New']
    template_name = 'dash/dashboard.html'
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})


class AnalysComplexDataView(GroupRequiredMixin, View):
    group_required = ['premium']
    template_name = 'dash/analys_complex_data.html'
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})
    

class AnalysSimpleDataView(GroupRequiredMixin, View):
    group_required = ['New']
    template_name = 'dash/analys_simple_data.html'
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})
    
    
@group_required(['basic'])
def student_dashboard(request):
    
    user = request.user 
    
    if user.has_perm('compte.can_view_payment_history'): #app_label.codename
        
        messages.info(request, 'you can view payment history ')
    else:
        messages.info(request, 'you can not view payment history')   
        
    if user.groups.filter(name='basic').exists():
        messages.info(request, 'you are in basic group')     

    return render(request, 'dash/student_dashboard.html')


from django.contrib.auth.models import Group, Permission
import datetime 


def payment(request, *args, **kwargs):
    plans = Plan.objects.all()
    
    if request.method == 'POST':
        user = request.user 
        plan_id = request.POST.get('type_plan')
        
        period = request.POST.get('period')
        if plan_id == 'premium':
            if period=='monthly':
                SubcribePlam.objects.create(user=user, plan_id=plan_id,
                                            start_date=datetime.datetime.now(),
                                            end_date=datetime.datetime.now() + datetime.timedelta(days=30))
            elif period == 'yearly':
                
                SubcribePlam.objects.create(user=user, plan_id=plan_id,
                                            start_date=datetime.datetime.now(),
                                            end_date=datetime.datetime.now() + datetime.timedelta(days=365))
                    
            permission = Permission.objects.get(codename='can_view_payment_history')
            
            user.user_permissions.add(permission)
            
            messages.info(request, 'you have  been added to view history payment')
            
            groups = Group.objects.filter(name__in=['premium', 'basic', 'New'])
        
        
            user.groups.set(groups)
            
            messages.info(request, 'you have  been added to basic group')
            
            messages.success(request, 'you have successfully subscribed to a plan')
            
        elif plan_id == 'basic':
            SubcribePlam.objects.create(user=user, plan_id=plan_id,
                                        start_date='2023-10-05',
                                        end_date='2023-12-01')
            
            groups = Group.objects.filter(name__in=['basic', 'New'])
        
        
            user.groups.set(groups)
            
            messages.info(request, 'you have  been added to basic group')
            
            messages.success(request, 'you have successfully subscribed to a plan')   
        else:
            SubcribePlam.objects.create(user=user, plan_id=plan_id,
                                        start_date='2023-10-05',
                                        end_date='2023-12-01')
            
            groups = Group.objects.filter(name__in=['New'])
        
        
            user.groups.set(groups)
            
            messages.info(request, 'you have  been added to New group')
            
            messages.success(request, 'you have successfully subscribed to a plan')     
    return render(request, 'dash/payment.html', {'plans': plans})


def my_task_view(request):
    
    result = add.delay(2, 3)
    
    print(result)

    return render(request, 'dash/my_task.html', {'result': result})


def my_task_result(request, task_id):

    result = add.AsyncResult(task_id)
    
    if result.ready():

        return render(request, 'dash/my_task_result.html', {'result': result.result})
    
    else:
        return render(request, 'dash/my_task_result.html', {'result': 'task is not ready still running'})
    

dashboard/templates/dash/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if messages %}

    {% for message in messages %}

    <p style="color: green"> {{ message }}</p>

    {% endfor %}

{% endif %}

    <h1> Bienvenue sur le tableau de bord ..........................</h1>
    
</body>
</html>

dashboard/templates/dash/my_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1> Id de la tache {{ result }} </h1>

    <a href="{% url 'dashboard:task-result' result %}"> voir le resulta de la tache </a>
    
</body>
</html>

dashboard/templates/dash/my_task_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

 <h1> result is : {{result}} </h1>
    
</body>
</html>

dashboard/templates/dash/payment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if messages %}

    {% for message in messages %}

    <p style="color: green"> {{ message }}</p>

    {% endfor %}

{% endif %}

    <h1> Bienvenue  sur payment..........................</h1>


    <form action="" method="post">
        {% csrf_token %}
        <select name="type_plan" id="" placeholder="choissir votre plan ">
            {% for plan in plans %}
            <option value="{{plan.pk}}">{{plan.name}} {{plan.price}}</option>
            {% endfor %}
        </select>
        <br>
        
        <input type="submit" name="submit" value="payer">
    </form>    
    
</body>
</html>

dashboard/templates/dash/student_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if messages %}

    {% for message in messages %}

    <p style="color: green"> {{ message }}</p>

    {% endfor %}

{% endif %}


{% comment %} {% if request.user.is_authenticated %}   
    <a> Bonjour {{ request.user.username }} </a>
    <a href="{% url 'logout' %}">Logout</a>
    <a href="{% url 'password_change' %}">Change Password</a>
   
    <a> analytics  {% if request.user.has_perm('compte.can_view_payment_history')%} ouvert{% else %} ferme{%endif%}</a>
    <a> analytics  {% if request.user.groups.filter(name='basic')%} ouvert{% else %} ferme{%endif%}</a>
    <a> dashboard</a>
{% else %}    

    <h1> Bienvenue  sur student..........................</h1>
    <a href="{% url 'login' %}">Login</a>
    <a href="{% url 'register' %}">Register</a>
    <a href="{% url 'password_reset' %}">Reset Password</a>
    
{% endif %} {% endcomment %}
</body>
</html>