compte/urls.py
from django.urls import path 
from . import views

from .custom_views import CreatePlanView, ListPlanView, CreatePlanView2

app_name = 'compte'

custom_patterns = [
    path('create-plan/', CreatePlanView.as_view(), name='create-plan'),
    path('create-plan2/', CreatePlanView2.as_view(), name='create-plan2'),
    path('list-plan/', ListPlanView.as_view(), name='list-plan'),
]


urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('activate/<uid64>/<token>/', views.activate, name="activate"),
    path('logout/', views.logout_view, name='logout'),
    path('reset-password-email/', views.ResetPassworLinkView.as_view(), name='reset-password-email'),
    path('reset-password/<uid64>/<token>/', views.password_reset_verification, name='reset-password-verify'),
    path('reset-password-complete/', views.password_reset_html, name='reset-password-complete'),
]


urlpatterns += custom_patterns


# Bon  a savoir django possede de vue preconstruite 

# exemple:

from django.contrib.auth import views as auth_views
from django.urls import path

urlpatterns = [
    # ... your other URL patterns ...

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

easy_dea/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path


## about/fr

urlpatterns = i18n_patterns(
    path("easy-dea-admin/", admin.site.urls),
    path("", include("main_app.urls")),
    path('compte/', include('compte.urls')),
    path('dashboard/', include('dashboard.urls')),
    
)

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


"""

from main_app import views

from main_app.custom_views.accounts import (
    RegisterView,
    SignupView,
)

from main_app.views import (
    MyView,
    HomePageView,
    AboutUsView,
    AboutView, 
    TermOfUseView,
    PrivacyPolicyView,
    SupportView,
    ContactUsView,
    ComplaintsView,
    FeedbackView,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main_app.urls")),
    path("home/", HomePageView.as_view(), name="home"),

    path('hello/', views.hello),
    path("mine/", MyView.as_view(), name="my-view"),
    
  #  path("about-us/", AboutUsView.as_view(), name="about-us"),
    path('about-us/', AboutView.as_view(), name='about-us'),
    path("term-of-use", TermOfUseView.as_view(), name="term-of-use"),
    path("privacy-policy", PrivacyPolicyView.as_view(), name="privacy-policy"),
    path("support", SupportView.as_view(), name="support"),
    path("contact-us", ContactUsView.as_view(), name="contact-us"),
    path("complaints", ComplaintsView.as_view(), name="complaints"),
    path("feedback", FeedbackView.as_view(), name="feedback"),
    
    path("sign-up", SignupView.as_view(), name="sign-up"),
    path("register", RegisterView.as_view(), name="register"),
    
]
"""

main_app/urls.py
from django.urls import path
from .views import create_datesete, DataSetCreationView, modify_dataset, list_dataset, delete_dataset
from main_app.custom_views.accounts import (
    RegisterView,
    SignupView,
)
from main_app.custom_views.commons import (
    ContactUsView,
    AboutUsView,
    HomePageView,
    AboutView, 
    TermOfUseView,
    PrivacyPolicyView,
    SupportView,
    ContactUsView,
    ComplaintsView,
    FeedbackView,
    ServicesView,

)

app_name = 'main_app'

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path('about-us/', AboutView.as_view(), name='about-us'),
    path("term-of-use", TermOfUseView.as_view(), name="term-of-use"),
    path("privacy-policy", PrivacyPolicyView.as_view(), name="privacy-policy"),
    path("support", SupportView.as_view(), name="support"),
    path("contact-us", ContactUsView.as_view(), name="contact-us"),
    path("complaints", ComplaintsView.as_view(), name="complaints"),
    path("feedback", FeedbackView.as_view(), name="feedback"),
    path("services", ServicesView.as_view(), name="services"),
    
    path("sign-up", SignupView.as_view(), name="sign-up"),
    path("register", RegisterView.as_view(), name="register"),
    
    path('create-dataset/', create_datesete, name='create-dataset'),
    path('modify-dataset/<int:pk>/', modify_dataset, name='modify-data'),
    path('delete-dataset/<int:pk>/', delete_dataset, name='delete-data'),
    path('list-dataset/', list_dataset, name='list-dataset')
    
   # path('create-dataset/', DataSetCreationView.as_view(), name='create-dataset'),
]

templates/includes/_footer.html
{% load static %}
{% load i18n %}
{% load l10n %}
<!-- footer start -->

  

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6">
            <div class="footer-info">

              <a href="" class="logo"><img src="{% static 'img/logo2.svg' %}"  width="129" height="74" alt="" class="img-fluid"></a>
              
              <!--<h3>Easy-DEA</h3>-->
              <p class="mt-3">
                <strong>{% trans 'Easy-dea is a digital platform developed by Jinoo, Inc. to popularize efficiency analysis' %}</strong>
              </p> 
              <p class="mt-3">
                1072 Abbott Street,Milton, ON L9T5P4<br>
                Canada <br><br>
                <strong>{% trans 'Telephon' %}:</strong> {{ site.contact_number }}<br>
                <strong>Email:</strong> {{ site.support_email|default_if_none:'contact@jinoo.ca' }}<br>
              </p>
              <div class="social-links mt-3">
                <a href="{{ site.twitter_url }}" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="{{ site.facebook_url }}" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="{{ site.instagram_url }}" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="{{ site.linkedin_url }}" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="{{ site.linkedin_url }}" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                <a href="{{ site.youtube_url }}" class="youtube"><i class="bx bxl-youtube"></i></a>
              </div>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>{% trans 'Useful Links' %}</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main_app:home' %}">{% trans 'Home' %}</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main_app:term-of-use' %}">{% trans 'Term of use' %}</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main_app:privacy-policy' %}">{% trans 'Confidentiality policy' %}</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main_app:term-of-use' %}">{% trans 'Property rights' %}</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main_app:term-of-use' %}">{% trans 'Regulatory Affairs' %}</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main_app:term-of-use' %}">{% trans 'Professional code of conduct' %}</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main_app:term-of-use' %}">{% trans 'Cookies settings' %}</a></li>
            </ul>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>{% trans 'Contact us' %}</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main_app:support' %}">{% trans 'Assistance and help' %}</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main_app:contact-us' %}">{% trans 'Contact us' %}</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main_app:complaints' %}">{% trans 'Complaints' %}</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main_app:feedback' %}">{% trans 'Feedback' %}</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>{% trans 'Our newsletter' %} </h4>
            <p>{% trans 'Subscribe to our newsletter to stay up to date with all the advances in the field of organizational efficiency analysis.' %}</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Jinoo Inc</span></strong>. {% trans 'All Rights Reserved' %} 
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/day-multipurpose-html-template-for-free/ -->
        {% trans 'Designed by' %}  <a href="https://bootstrapmade.com/">Jinoo Inc</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  <!--<div id="preloader"></div> -->

templates/includes/_footer0.html
{% load static %}
{% load i18n %}
{% load l10n %}
<!-- footer start -->


  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6">
            <div class="footer-info">
              <h3>Easy-DEA</h3>
              <p>
                1072 Abbott Street <br>
                Milton, ON L9T5P4<br>
                Canada <br><br>
                <strong>Téléphone:</strong> +1 819 640 9006<br>
                <strong>Email:</strong> info@easy-dea.com<br>
              </p>
              <div class="social-links mt-3">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
              </div>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Liens utiles</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Apropos de nous</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Conditions d’utilisation</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Politique de confidentialité </a></li>  
            </ul>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Nos Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Mesure de l'efficience</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Développement des algorithmes</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Consultation</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Suivi-évaluation</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Tableau de bord</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Notre infolettre</h4>
            <p>Souscrire à notre infolettre pour rester au courant de toutes les avancées dans le domaine de l'analyse de l'efficience des organisations.</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Jinoo Inc</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/day-multipurpose-html-template-for-free/ -->
        Designed by <a href="https://bootstrapmade.com/">Jinoo Inc</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  <div id="preloader"></div>

templates/includes/_header.html
{% load static %}
{% load i18n %}
{% load l10n %}

{% load widget_tweaks %}

<!--{% load helper_tags %}-->
{% get_available_languages as languages %}
<!-- ======= Top Bar ======= -->
<section id="topbar" class="d-flex align-items-center pt-3 pb-3">
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope-fill"></i><a href="mailto:{{ site.support_email|default_if_none:'contact@jinoo.ca' }}">{{ site.support_email|default_if_none:'contact@jinoo.ca' }}</a>
        <i class="bi bi-phone-fill phone-icon"></i><a href="tel:{{ site.contact_number }}">{{ site.contact_number }}</a> 
      </div>
      <div class="social-links d-none d-md-block">
        <a href="" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
      </div>

      

      <div class="d-flex justify-content-center ">
        <a class="btn btn-primary btn-warning fw-bold text-center" href="{% url 'main_app:sign-up' %}" role="button">{% trans 'Sign In' %}</a>
        <a class="btn btn-outline-warning mx-3 fw-bold text-center" href="inscription.html" role="button">S'inscrire</a>
      </div>      
    </div>
  </section>

templates/includes/_jsfile.html
{% load static %}
{% load i18n %}
{% load l10n %}

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/aos/aos.js' %} "></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %} "></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %} "></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %} "></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %} "></script>

  <!-- Template Main JS File -->
  <script src="{% static '' %}"></script>

templates/includes/_menu.html
{% load static %}
{% load i18n %}
{% load l10n %}

{% load widget_tweaks %}


{% get_available_languages as languages %}
 <!-- ======= Header ======= -->
 <header id="header" class="d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <!-- <h1 class="logo"><a href="index.html">Day</a></h1> -->
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      <a href="index.html" class="logo"><img src="{% static 'img/logo2.svg' %}"  width="129" height="74"  alt="" class="img-fluid"></a>

      <nav id="navbar" class="navbar">
        <ul>
          <!-- <li><a class="nav-link scrollto active" href="#hero">Acceuil</a> -->
          <li><a class="nav-link scrollto" href="{% url 'main_app:home' %}"> {% trans 'Home' %}</a>          </li>
          <li><a class="nav-link scrollto" href="{% url 'main_app:services' %}">{% trans 'Services' %}</a></li>
          <li class="dropdown"><a href="model.html"><span>{% trans 'Models' %}</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              
              <li class="dropdown"><a href="#"><span>{% trans 'Technical efficiency ' %}</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                    <li class="dropdown"><a href="#"><span>{% trans 'One period ' %}</span><i class="bi bi-chevron-right"></i></a>
                        <ul>
                            <li><a href="#">{% trans 'Basic ' %}</a></li>
                            <li><a href="#">{% trans 'Alternate basic ' %}</a></li>
                            <li><a href="#">{% trans 'Intermediate ' %}</a></li>
                            <li><a href="#">{% trans 'Advanced ' %}</a></li>
                            <li><a href="#">{% trans 'very advanced ' %}</a></li>
                            <li><a href="#">{% trans 'Networks ' %}</a></li>
                        </ul>
                    </li>
                    <li class="dropdown"><a href="#"><span>{% trans 'Multi period ' %}</span><i class="bi bi-chevron-right"></i></a>
                        <ul>
                            <li><a href="#">{% trans 'Basic ' %}</a></li>
                            <li><a href="#">{% trans 'Alternate basic ' %}</a></li>
                            <li><a href="#">{% trans 'Intermediate ' %}</a></li>
                            <li><a href="#">{% trans 'Advanced ' %}</a></li>
                            <li><a href="#">{% trans 'very advanced ' %}</a></li>
                            <li><a href="#">{% trans 'Networks ' %}</a></li>
                        </ul>
                    </li>
                </ul>
              </li>
              <li class="dropdown"><a href="#"><span>{% trans 'Cost efficiency ' %} </span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                    <li class="dropdown"><a href="#"><span>{% trans 'One period ' %}</span><i class="bi bi-chevron-right"></i></a>
                        <ul>
                            <li><a href="#">{% trans 'Basic ' %}</a></li>
                            <li><a href="#">{% trans 'Alternate basic ' %}</a></li>
                            <li><a href="#">{% trans 'Intermediate ' %}</a></li>
                            <li><a href="#">{% trans 'Advanced ' %}</a></li>
                            <li><a href="#">{% trans 'very advanced ' %}</a></li>
                            <li><a href="#">{% trans 'Networks ' %}</a></li>
                        </ul>
                    </li>
                    <li class="dropdown"><a href="#"><span>{% trans 'Multi period ' %}</span><i class="bi bi-chevron-right"></i></a>
                        <ul>
                            <li><a href="#">{% trans 'Basic ' %}</a></li>
                            <li><a href="#">{% trans 'Alternate basic ' %}</a></li>
                            <li><a href="#">{% trans 'Intermediate ' %}</a></li>
                            <li><a href="#">{% trans 'Advanced ' %}</a></li>
                            <li><a href="#">{% trans 'very advanced ' %}</a></li>
                            <li><a href="#">{% trans 'Networks ' %}</a></li>
                        </ul>
                    </li>     </ul>
              </li>
              <li class="dropdown"><a href="#"><span>{% trans 'Income efficiency ' %} </span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                    <li class="dropdown"><a href="#"><span>{% trans 'One period ' %}</span><i class="bi bi-chevron-right"></i></a>
                        <ul>
                            <li><a href="#">{% trans 'Basic ' %}</a></li>
                            <li><a href="#">{% trans 'Alternate basic ' %}</a></li>
                            <li><a href="#">{% trans 'Intermediate ' %}</a></li>
                            <li><a href="#">{% trans 'Advanced ' %}</a></li>
                            <li><a href="#">{% trans 'very advanced ' %}</a></li>
                            <li><a href="#">{% trans 'Networks ' %}</a></li>
                        </ul>
                    </li>
                    <li class="dropdown"><a href="#"><span>{% trans 'Multi period ' %}</span><i class="bi bi-chevron-right"></i></a>
                        <ul>
                            <li><a href="#">{% trans 'Basic ' %}</a></li>
                            <li><a href="#">{% trans 'Alternate basic ' %}</a></li>
                            <li><a href="#">{% trans 'Intermediate ' %}</a></li>
                            <li><a href="#">{% trans 'Advanced ' %}</a></li>
                            <li><a href="#">{% trans 'very advanced ' %}</a></li>
                            <li><a href="#">{% trans 'Networks ' %}</a></li>
                        </ul>
                    </li>
                </ul>
              </li>
              <li class="dropdown"><a href="#"><span>{% trans 'Profit efficiency ' %}</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                    <li class="dropdown"><a href="#"><span>{% trans 'One period ' %}</span><i class="bi bi-chevron-right"></i></a>
                        <ul>
                            <li><a href="#">{% trans 'Basic ' %}</a></li>
                            <li><a href="#">{% trans 'Alternate basic ' %}</a></li>
                            <li><a href="#">{% trans 'Intermediate ' %}</a></li>
                            <li><a href="#">{% trans 'Advanced ' %}</a></li>
                            <li><a href="#">{% trans 'very advanced ' %}</a></li>
                            <li><a href="#">{% trans 'Networks ' %}</a></li>
                        </ul>
                    </li>
                    <li class="dropdown"><a href="#"><span>{% trans 'Multi period ' %}</span><i class="bi bi-chevron-right"></i></a>
                        <ul>
                            <li><a href="#">{% trans 'Basic ' %}</a></li>
                            <li><a href="#">{% trans 'Alternate basic ' %}</a></li>
                            <li><a href="#">{% trans 'Intermediate ' %}</a></li>
                            <li><a href="#">{% trans 'Advanced ' %}</a></li>
                            <li><a href="#">{% trans 'very advanced ' %}</a></li>
                            <li><a href="#">{% trans 'Networks ' %}</a></li>
                        </ul>
                    </li>
                </ul>
              </li>
              <li><a href="#">{% trans 'Productivity index' %} </a></li>
            </ul>
          </li>
          <!-- <li><a class="nav-link scrollto " href="#portfolio">portefeuilles</a>-->
          </li>

          <li class="dropdown"><a href="#"><span>{% trans 'Applications' %}</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
                <li class="dropdown"><a href="#"><span>{% trans 'Publications ' %}</span><i class="bi bi-chevron-right"></i></a>
                    <ul>
                        <li><a href="#">{% trans 'Bank and Insurance ' %}</a></li>
                        <li><a href="#">{% trans 'Health and healthcare ' %}</a></li>
                        <li><a href="#">{% trans 'Transport ' %}</a></li>
                        <li><a href="#">{% trans 'Other sectors ' %}</a></li>
                    </ul>
                </li>                
                <li class="dropdown"><a href="#"><span>{% trans 'Our Examples ' %}</span><i class="bi bi-chevron-right"></i></a>
                    <ul>
                        <li><a href="#">{% trans 'Technical efficiency ' %}</a></li>
                        <li><a href="#">{% trans 'Cost efficiency ' %}</a></li>
                        <li><a href="#">{% trans 'Income efficiency ' %}</a></li>
                        <li><a href="#">{% trans 'Profit efficiency ' %}</a></li>
                        <li><a href="#">{% trans 'Productivity index' %}</a></li>
                    </ul>
                </li> 
            </ul>            
          </li> 
          
            <li class="dropdown"><a href=""><span>{% trans 'Ressources' %}</span> <i class="bi bi-chevron-down"></i></a>
                <ul>
                    <li><a href="#">{% trans 'Documentation & tools ' %}</a></li>
                    <li><a href="#">{% trans 'Events ' %}</a></li>
                    <li><a href="#">{% trans 'Videos ' %}</a></li>
                </ul>
            </li> 
            <li><a class="nav-link scrollto" href="">{% trans 'Price' %}</a></li>
            <li><a class="nav-link scrollto" href="">{% trans 'News' %}</a></li>
            <li><a class="nav-link scrollto" href="{% url 'main_app:contact-us' %}">{% trans 'Contact' %}</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

templates/includes/_metas.html
{% load static %}
{% load i18n %}
{% load l10n %}

<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1.0" name="viewport">

<meta name="author" content="JINOO Inc">

<meta content="" name="description">
<meta content="DEA, efficiency, " name="keywords">

<!-- Favicons -->

<link href="{% static 'img/favicon.png' %} " rel="icon">
<link href="{% static 'img/apple-touch-icon.png' %} " rel="apple-touch-icon">
<link href="{% static 'img/favicon.png' %} " rel="icon">

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

<!-- Vendor CSS Files -->
<link href="{% static 'vendor/aos/aos.css' %} " rel="stylesheet">
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">
<link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %} " rel="stylesheet">
<link href="{% static 'vendor/boxicons/css/boxicons.min.css' %} " rel="stylesheet">
<link href="{% static 'vendor/glightbox/css/glightbox.min.css' %} " rel="stylesheet">
<link href="{% static 'vendor/swiper/swiper-bundle.min.css' %} " rel="stylesheet">


<!-- Template Main CSS File -->
<link href="{% static 'css/style.css' %} " rel="stylesheet">

<!-- =======================================================
* Template Name: Day
* Updated: May 30 2023 with Bootstrap v5.3.0
* Template URL: https://bootstrapmade.com/day-multipurpose-html-template-for-free/
* Author: BootstrapMade.com
* License: https://bootstrapmade.com/license/
======================================================== -->

<!--<title>Day Bootstrap Template - Index</title> -->
<title>{{ site.title }}</title>